name: Auto Generator

on:
  push:
    branches:
      - AutoGenerator
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  Auto_Generator:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.git_auto_commit.outputs.changes_detected }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Auto Generator
        run: "chmod -R a+w AutoGenerator && docker run -v .:/output -v $PWD/AutoGenerator/AutoGenerator/appsettings.json:/app/appsettings.json ghcr.io/youtubeclipplaylist/playlistautogenerator"

      - name: Git Auto Commit
        id: git_auto_commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: AutoGenerator
          file_pattern: AutoGenerator
          commit_message: "Github Action: Auto Generator"
          commit_user_name: Github Action Bot # defaults to "GitHub Actions"
          commit_author: Github Action Bot <actions@github.com> # defaults to author of the commit that triggered the run

  Auto_PR:
    needs: Auto_Generator
    if: needs.Auto_Generator.outputs.changes_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: AutoGenerator

      - name: Create or Update Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh_pr_up() {
            gh pr create "$@" || gh pr edit "$@"
          }

          gh_pr_up --title "AutoGenerator to master auto PR" \
                   --body ":robot: Automated PR from **AutoGenerator** to **master**" \
                   --label automerge \
                   --base master \
                   --head AutoGenerator
        shell: bash
