name: JSON Syntax Check

on:
  pull_request:
    paths-ignore:
      - "AutoGenerator/**"

jobs:
  json-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove AutoGenerator
        run: rm -rf AutoGenerator

      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2.0.2
        with:
          pattern: "\\.jsonc$"
