name: Minify

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Minify_Action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: zofrex/mirror-branch@v1.0.4
        with:
          target-branch: minify

      # Use https://github.com/Josee9988/MinifyAllCli
      - name: Minify Action
        run: "npx @josee9988/minifyall -d ."

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: minify
          commit_message: "Github Action: Auto Minified HTML CSS JSON JSONC"
          commit_user_name: Minify Action Bot # defaults to "GitHub Actions"
          commit_author: Minify Action Bot <actions@github.com> # defaults to author of the commit that triggered the run
